MONTHS_A = ["january", "february", "march", "april", "may", "june","july", "august", "september","october", "november", "december"]
MONTHS_a = ["jan", "feb", "mar", "apr", "may", "jun","jul", "aug", "sep","oct", "nov", "dec"]
DAYS_B= ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
DAYS_b = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
DAY_EXTENTIONS = ["rd", "th", "st", "nd"]
